In [1]:
import numpy as np
import pandas as pd

# Concatenate

In [2]:
arr1 = np.random.randn(9).reshape(3,3)

In [3]:
arr1

array([[-1.01109177,  0.65016436,  0.63124595],
       [-0.65302927, -0.23698523, -0.35093325],
       [ 1.92882177, -0.90865162,  0.71748449]])

In [4]:
arr2 = np.arange(10,1,-1).reshape(3,3)

In [5]:
arr2

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

In [6]:
np.concatenate([arr1,arr2])

array([[-1.01109177,  0.65016436,  0.63124595],
       [-0.65302927, -0.23698523, -0.35093325],
       [ 1.92882177, -0.90865162,  0.71748449],
       [10.        ,  9.        ,  8.        ],
       [ 7.        ,  6.        ,  5.        ],
       [ 4.        ,  3.        ,  2.        ]])

In [7]:
np.concatenate([arr1,arr2],axis=1)

array([[-1.01109177,  0.65016436,  0.63124595, 10.        ,  9.        ,
         8.        ],
       [-0.65302927, -0.23698523, -0.35093325,  7.        ,  6.        ,
         5.        ],
       [ 1.92882177, -0.90865162,  0.71748449,  4.        ,  3.        ,
         2.        ]])

In [8]:
s1 = pd.Series([1,2,3],index=['x','y','z'])
s2 = pd.Series([4,5],index=['a','b'])

In [9]:
pd.concat([s1,s2])

x    1
y    2
z    3
a    4
b    5
dtype: int64

In [10]:
pd.concat([s1,s2],axis=1)

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.


0    1
a  NaN  4.0
b  NaN  5.0
x  1.0  NaN
y  2.0  NaN
z  3.0  NaN

In [11]:
df1 = pd.DataFrame(np.random.randn(12).reshape(4,3),columns=list('abc'))
df1

a         b         c
0  0.020467  0.482554 -2.185318
1  0.892960  0.755916 -0.186849
2 -2.511041 -1.285518 -2.220171
3 -1.997599  0.440635  1.457040

In [12]:
df2 = pd.DataFrame(np.random.randn(9).reshape(3,3),columns=list('abx'))
df2

a         b         x
0 -0.047896  0.825900 -0.316438
1 -0.671577  1.529939 -1.162876
2  0.900324  0.096827 -1.084222

In [13]:
pd.concat([df1,df2])

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.


a         b         c         x
0  0.020467  0.482554 -2.185318       NaN
1  0.892960  0.755916 -0.186849       NaN
2 -2.511041 -1.285518 -2.220171       NaN
3 -1.997599  0.440635  1.457040       NaN
0 -0.047896  0.825900       NaN -0.316438
1 -0.671577  1.529939       NaN -1.162876
2  0.900324  0.096827       NaN -1.084222

In [14]:
pd.concat([df1,df2],axis=1)

a         b         c         a         b         x
0  0.020467  0.482554 -2.185318 -0.047896  0.825900 -0.316438
1  0.892960  0.755916 -0.186849 -0.671577  1.529939 -1.162876
2 -2.511041 -1.285518 -2.220171  0.900324  0.096827 -1.084222
3 -1.997599  0.440635  1.457040       NaN       NaN       NaN

# Combine
* 填充

In [15]:
s3 = pd.Series([2,np.nan,4,np.nan],index=list('abcd'))
s3

a    2.0
b    NaN
c    4.0
d    NaN
dtype: float64

In [16]:
s4 = pd.Series([1,2,3,4],index=list('abcd'))
s4

a    1
b    2
c    3
d    4
dtype: int64

In [17]:
s3.combine_first(s4) # 讲s4数据填充到s3的NaN

a    2.0
b    2.0
c    4.0
d    4.0
dtype: float64

In [18]:
df3 = pd.DataFrame({
    'X': [1, np.nan, 3, np.nan],
    'Y': [5, np.nan, 7, np.nan],
    'Z': [9, np.nan, 11,np.nan]
})
df3

X    Y     Z
0  1.0  5.0   9.0
1  NaN  NaN   NaN
2  3.0  7.0  11.0
3  NaN  NaN   NaN

In [19]:
df4 = pd.DataFrame({
    'Z':[np.nan, 10, np.nan, 12],
    'A':[1,2,3,4]
})
df4

Z  A
0   NaN  1
1  10.0  2
2   NaN  3
3  12.0  4

In [20]:
df3.combine_first(df4)

A    X    Y     Z
0  1.0  1.0  5.0   9.0
1  2.0  NaN  NaN  10.0
2  3.0  3.0  7.0  11.0
3  4.0  NaN  NaN  12.0