In [1]:
import pickle
import numpy as np

In [2]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# 使用pickle序列化numpy array

## 写入

In [3]:
f = open('x.pkl','wb') # wb：写二进制

In [4]:
pickle.dump(x,f)# 把文件序列化到20181104Numpy_03输入输出.ipynb所在同一文件夹

In [5]:
f = open('x.pkl','rb')

## 读取

In [6]:
pickle.load(f)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
np.save('one_array',x)

In [8]:
np.load('one_array.npy')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
y = np.arange(10)

In [10]:
np.savez('two_array',a=x,b=y)

In [11]:
c = np.load('two_array.npz')
c

In [12]:
c['a']

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
c['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

[官网]（https://docs.scipy.org/doc/numpy/)