In [1]:
import numpy as np

In [2]:
a = np.random.randint(10,size=20).reshape(4,5)
b = np.random.randint(10,size=20).reshape(4,5)
a

array([[1, 9, 0, 4, 4],
       [8, 6, 4, 9, 5],
       [3, 9, 2, 0, 9],
       [3, 4, 6, 5, 6]])

In [3]:
b

array([[5, 9, 8, 3, 3],
       [6, 9, 4, 1, 7],
       [1, 6, 0, 4, 1],
       [6, 5, 8, 7, 1]])

## 数组运算

In [4]:
a + b

array([[ 6, 18,  8,  7,  7],
       [14, 15,  8, 10, 12],
       [ 4, 15,  2,  4, 10],
       [ 9,  9, 14, 12,  7]])

In [5]:
a - b

array([[-4,  0, -8,  1,  1],
       [ 2, -3,  0,  8, -2],
       [ 2,  3,  2, -4,  8],
       [-3, -1, -2, -2,  5]])

In [6]:
a * b

array([[ 5, 81,  0, 12, 12],
       [48, 54, 16,  9, 35],
       [ 3, 54,  0,  0,  9],
       [18, 20, 48, 35,  6]])

In [7]:
a/b

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.2       , 1.        , 0.        , 1.33333333, 1.33333333],
       [1.33333333, 0.66666667, 1.        , 9.        , 0.71428571],
       [3.        , 1.5       ,        inf, 0.        , 9.        ],
       [0.5       , 0.8       , 0.75      , 0.71428571, 6.        ]])

## 矩阵运算

In [8]:
A = np.mat(a)
B = np.mat(b)
A

matrix([[1, 9, 0, 4, 4],
        [8, 6, 4, 9, 5],
        [3, 9, 2, 0, 9],
        [3, 4, 6, 5, 6]])

In [9]:
B

matrix([[5, 9, 8, 3, 3],
        [6, 9, 4, 1, 7],
        [1, 6, 0, 4, 1],
        [6, 5, 8, 7, 1]])

In [10]:
A + B

matrix([[ 6, 18,  8,  7,  7],
        [14, 15,  8, 10, 12],
        [ 4, 15,  2,  4, 10],
        [ 9,  9, 14, 12,  7]])

In [11]:
A - B

matrix([[-4,  0, -8,  1,  1],
        [ 2, -3,  0,  8, -2],
        [ 2,  3,  2, -4,  8],
        [-3, -1, -2, -2,  5]])

In [12]:
A * B.T #(mxp * pxn = mxn)

matrix([[110, 119,  75,  83],
        [168, 162,  85, 178],
        [139, 170,  66,  88],
        [132, 125,  53, 127]])

## Array常见函数

In [13]:
a

array([[1, 9, 0, 4, 4],
       [8, 6, 4, 9, 5],
       [3, 9, 2, 0, 9],
       [3, 4, 6, 5, 6]])

In [14]:
np.unique(a)

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [15]:
sum(a)

array([15, 28, 12, 18, 24])

In [16]:
sum(a[0])

18

In [17]:
sum(a[:,0])

15

In [18]:
a.max()

9

In [19]:
max(a[0])

9