In [1]:
import numpy as np

## 创建

In [2]:
list_1 = [1,2,3,4]
array_1 = np.array(list_1,dtype='float')
array_1

array([1., 2., 3., 4.])

In [3]:
list_2 = [5,6,7,8]
array_2 = np.array([list_1,list_2])
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
array_2.shape

(2, 4)

In [5]:
array_2.size

8

In [6]:
array_2.dtype

dtype('int32')

In [7]:
array_3 = np.arange(1,20,3)
array_3

array([ 1,  4,  7, 10, 13, 16, 19])

In [8]:
array_4 = np.zeros([2,3])
array_4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
array_5 = np.eye(3)
array_5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
array_6 = np.random.randn(3)
array_6

array([-0.76853739, -0.7618256 ,  0.33449129])

In [11]:
np.random.randint(10,20,size=(3,4))

array([[17, 14, 14, 13],
       [18, 11, 11, 16],
       [17, 12, 18, 15]])

In [12]:
np.random.randint(10,size=(3,3))

array([[9, 9, 5],
       [5, 4, 2],
       [6, 5, 3]])

In [13]:
np.random.randint(20,size=3)

array([11, 17, 13])

In [14]:
np.random.randint(10,size=12).reshape(3,4)

array([[8, 6, 3, 1],
       [8, 0, 0, 2],
       [5, 3, 5, 8]])

## 访问数组元素

In [15]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a[1]

1

In [17]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b = np.array(np.arange(12).reshape(3,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
b[1][0]

4

In [20]:
b[1,0]

4

In [21]:
b[:2,2:]

array([[2, 3],
       [6, 7]])