# numpy
* python 科学计算基础库
* 广播功能的函数
* N维数组对象 ndarray

* axis:轴，保存数据的维度
* rank：秩，轴的数量

## ndarray对象的属性
1. .ndim 秩，轴的数量或维度的数量
2. .shape ndarray对象的尺度，对于矩阵 n行m列
3. .size ndarray元素的个数，相当于.shape中n*m的值
4. .dtype ndarray对象的元素类型
5. .itemsize ndarray对象中每个元素的大小，以字节为单位

In [1]:
import numpy as np

In [2]:
type(np.nan)

float

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [12]:
a = np.random.randint(12,23,size=(3,4))

In [13]:
a

array([[14, 12, 13, 12],
       [21, 17, 19, 22],
       [20, 21, 20, 19]])

In [14]:
a.size

12

In [15]:
a.ndim

2

In [16]:
a.shape

(3, 4)

In [17]:
a.dtype

dtype('int32')

In [18]:
a.itemsize

4

## 非同质对象构成的ndarray数组
* 无法充分发挥numpy的优势
* 尽量避免使用

In [21]:
x = np.array([[1,2,3,4],[1,2,3]])#非同质对象构成的ndarray数组

In [22]:
x

array([list([1, 2, 3, 4]), list([1, 2, 3])], dtype=object)

In [23]:
x.dtype

dtype('O')

In [24]:
x.shape

(2,)

In [25]:
x.size

2

In [26]:
x.itemsize

4

# 创建

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [29]:
np.ones((3,4))#全1矩阵

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

* 最外层有2个元素
* 每个元素有3个维度
* 每个维度下有4个元素

In [30]:
np.zeros((2,3))#全0矩阵

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [33]:
np.eye(3)#单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [38]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [39]:
np.full_like(a,2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [41]:
x = np.linspace(1,10,4)#等间距

In [42]:
y = np.linspace(1,10,4,endpoint=False)

In [43]:
x

array([ 1.,  4.,  7., 10.])

In [44]:
y

array([1.  , 3.25, 5.5 , 7.75])

In [46]:
np.concatenate((x,y))#合并数组

array([ 1.  ,  4.  ,  7.  , 10.  ,  1.  ,  3.25,  5.5 ,  7.75])

# 数组变换

* a.reshape(shape)
    * 原数组不变
- a.resize(shape)
    * 原数组改变
* a.swapaxes(ax1,ax2)
	* 将数组n个维度中两个维度进行调换
* a.flatten()
	* 对数组进行降维
    * 返回折叠后的一维数组
    * 原数组不变

In [47]:
a = np.ones((2,3,4))

In [48]:
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [49]:
a.reshape(3,8)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [51]:
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [50]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
a.resize(3,8)#改变原数组

In [53]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [54]:
a.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [55]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

## 改变元素类型
* .astype()
    * np.int
    * np.float

In [58]:
a.dtype

dtype('float64')

In [59]:
a.astype(np.int)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [61]:
a.astype(np.int).dtype

dtype('int32')

## 改变为列表
* a.tolist()

In [64]:
c = a.tolist()

In [65]:
c

[[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]]

In [66]:
type(c)

list

# 数组的操作
* 切片
* 索引

In [69]:
np.arange(10)[0:-1:2]

array([0, 2, 4, 6, 8])

In [70]:
d = np.arange(24).reshape((2,3,4))

In [71]:
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

* 索引
    * 最外层
    * 第2个维度
    * 第3个维度

In [72]:
d[1,2,3]

23

* 切片

In [76]:
d[:,:,::2]

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])

# 数组的运算
* 数组与标量的运算，作用于数组每一个元素

In [78]:
d.mean()

11.5

In [79]:
d/d.mean()

array([[[0.        , 0.08695652, 0.17391304, 0.26086957],
        [0.34782609, 0.43478261, 0.52173913, 0.60869565],
        [0.69565217, 0.7826087 , 0.86956522, 0.95652174]],

       [[1.04347826, 1.13043478, 1.2173913 , 1.30434783],
        [1.39130435, 1.47826087, 1.56521739, 1.65217391],
        [1.73913043, 1.82608696, 1.91304348, 2.        ]]])

In [80]:
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [81]:
np.square(d)

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]],

       [[144, 169, 196, 225],
        [256, 289, 324, 361],
        [400, 441, 484, 529]]], dtype=int32)

In [94]:
e = np.sqrt(d)

In [95]:
d1,d2 = np.modf(e)

In [96]:
d1

array([[[0.        , 0.        , 0.41421356, 0.73205081],
        [0.        , 0.23606798, 0.44948974, 0.64575131],
        [0.82842712, 0.        , 0.16227766, 0.31662479]],

       [[0.46410162, 0.60555128, 0.74165739, 0.87298335],
        [0.        , 0.12310563, 0.24264069, 0.35889894],
        [0.47213595, 0.58257569, 0.69041576, 0.79583152]]])

In [97]:
d2

array([[[0., 1., 1., 1.],
        [2., 2., 2., 2.],
        [2., 3., 3., 3.]],

       [[3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]])

In [86]:
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [98]:
np.maximum(d,e)

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])

In [99]:
np.minimum(d,e)

array([[[0.        , 1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974, 2.64575131],
        [2.82842712, 3.        , 3.16227766, 3.31662479]],

       [[3.46410162, 3.60555128, 3.74165739, 3.87298335],
        [4.        , 4.12310563, 4.24264069, 4.35889894],
        [4.47213595, 4.58257569, 4.69041576, 4.79583152]]])

In [100]:
d>e

array([[[False, False,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [101]:
np.random.rand(2,3,4)

array([[[0.04521394, 0.17957628, 0.24588778, 0.53877894],
        [0.61719469, 0.10790526, 0.9598399 , 0.83958452],
        [0.45034052, 0.19013056, 0.44993867, 0.83735504]],

       [[0.66956187, 0.500928  , 0.76710039, 0.64690504],
        [0.69373177, 0.43892046, 0.01630147, 0.39249155],
        [0.10687229, 0.05311311, 0.24663608, 0.57755994]]])

In [102]:
np.random.randn(2,3,4)

array([[[-1.68590008,  2.26337457,  0.90500052, -0.55800997],
        [-0.360416  ,  0.76611024,  0.0089419 ,  1.28367938],
        [-1.50357558, -0.98403862,  0.21507765,  0.88137852]],

       [[-1.27563309, -0.96047033, -0.29815851, -2.43811585],
        [-1.00981974, -0.41435164,  0.31205519, -0.32231787],
        [ 0.0905856 ,  0.68868689,  0.03452749,  0.15232986]]])

In [105]:
np.random.randn(3,4)

array([[ 0.43593573,  0.15761978, -1.11017594,  0.72645821],
       [ 0.65195516, -0.96177297, -0.64314486,  0.23119136],
       [ 1.60230513, -1.87286792,  1.12123618,  0.32318229]])

In [108]:
np.random.randint(12,24,5)

array([14, 19, 19, 23, 14])

In [109]:
np.random.randint(12,24,(3,4))

array([[22, 16, 23, 22],
       [17, 17, 16, 20],
       [20, 18, 21, 14]])

In [111]:
np.random.seed(10)
np.random.randint(100,200,(3,4))

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [113]:
np.random.seed(10)
np.random.randint(100,200,(3,4))

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [115]:
f = np.random.randint(100,200,(3,4))

In [116]:
f

array([[116, 111, 154, 188],
       [162, 133, 172, 178],
       [149, 151, 154, 177]])

## np.random.shuffle(f)
* 根据数组f的第一轴进行随机排列
* 改变数组f

In [119]:
np.random.shuffle(f)

In [120]:
f

array([[149, 151, 154, 177],
       [116, 111, 154, 188],
       [162, 133, 172, 178]])

In [121]:
np.random.shuffle(f)

In [122]:
f

array([[162, 133, 172, 178],
       [149, 151, 154, 177],
       [116, 111, 154, 188]])

## np.random.permutation()
* 根据数组f的第1轴产生一个新的乱序数组
* 不改变数组f

In [124]:
np.random.permutation(f)

array([[149, 151, 154, 177],
       [162, 133, 172, 178],
       [116, 111, 154, 188]])

In [125]:
np.random.permutation(f)

array([[162, 133, 172, 178],
       [149, 151, 154, 177],
       [116, 111, 154, 188]])

## np.random.choice(a[,size,replace,p])
	* 从一维数组a中以概率p抽取元素
    * 形成size形状新数组
	* replace表示是否可以重用元素
        * 默认为False

In [129]:
e = np.random.randint(100,200,(8,))

In [130]:
e

array([177, 122, 123, 194, 111, 128, 174, 188])

In [131]:
np.random.choice(e,(2,3))

array([[122, 188, 123],
       [177, 174, 188]])

In [132]:
np.random.choice(e,(2,3),replace=False)

array([[123, 111, 128],
       [188, 174, 122]])

In [135]:
np.random.choice(e,(2,3),p=e/np.sum(e))

array([[122, 194, 188],
       [188, 194, 174]])

1. np.random.uniform(low,high,size)
	* 产生具有均匀分布的数组
	* low
		* 起始值
	* high
		* 结束值
	* size
		* 形状
2. np.random.normal(loc,scale,size)
	* 产生具有正态分布的数组
	* loc
		* 均值
	* scale
		* 标准差
	* size
		* 形状
	* np.random.normal(28,5,50)
		* 创建50个
        * 平均值为28
        * 标准差为5
        * 的随机数
		* 符合正态分布
3. np.random.poisson(lam,size)
	* 产生泊松分布的数组
	* lam
		* 随机事件发生概率
	* size
		* 形状

In [136]:
u = np.random.uniform(0,10,(3,4))

In [137]:
u

array([[2.51374134, 5.97371648, 9.0283176 , 5.34557949],
       [5.90201363, 0.39281767, 3.57181759, 0.7961309 ],
       [3.05459918, 3.30719312, 7.73830296, 0.39959209]])

In [138]:
n = np.random.normal(10,5,(3,3))

In [139]:
n

array([[ 1.00713488,  6.5739633 ,  2.95065566],
       [16.26199297, 12.34781381, 11.63460824],
       [19.04271603,  2.93466001, 22.61652543]])

# 统计函数

In [159]:
a =np.arange(15,0,-1).reshape(3,5)

In [160]:
a

array([[15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [161]:
np.sum(a)

120

In [162]:
np.sum(a,axis=1)

array([65, 40, 15])

In [163]:
np.sum(a,axis=0)

array([30, 27, 24, 21, 18])

In [164]:
np.mean(a)#期望

8.0

In [165]:
np.mean(a,axis=1)

array([13.,  8.,  3.])

In [166]:
np.mean(a,axis=0)

array([10.,  9.,  8.,  7.,  6.])

In [167]:
np.average(a,axis=0,weights=[10,5,1])# 加权平均

array([12.8125, 11.8125, 10.8125,  9.8125,  8.8125])

In [168]:
np.std(a)#标准差

4.320493798938574

In [169]:
np.var(a)#方差

18.666666666666668

In [170]:
np.max(a)

15

In [175]:
np.argmin(a)#最大值对应index的下标

14

In [173]:
np.unravel_index(np.argmin(a),a.shape)#重塑为多维下标

(2, 4)

In [176]:
np.ptp(a)# 极值之差

14

In [177]:
np.median(a)#中位数

8.0

# 梯度函数
* 梯度
    * 连续值之间的变化率
    * 即，斜率

* np.gradient(f)
    * 计算数组f中元素的梯度
    * 当f为多维时，返回每个维度的梯度

In [180]:
a1 = np.random.randint(0,20,5)

In [184]:
a1

array([ 3,  3, 18, 13, 11])

In [181]:
a1

array([ 3,  3, 18, 13, 11])

In [183]:
np.gradient(a1)

array([ 0. ,  7.5,  5. , -3.5, -2. ])

In [186]:
a2 = np.random.randint(0,20,(3,4))

In [187]:
np.gradient(a2)

[array([[-1.,  3., -3.,  2.],
        [ 3.,  6.,  1., -1.],
        [ 7.,  9.,  5., -4.]]), array([[-3. ,  1.5,  3. ,  0. ],
        [ 1. ,  0.5,  2.5,  5. ],
        [ 3. , -0.5, -4. , -4. ]])]