# ndarray
## Numpy的核心功能是‘ndarray’（n-dimensional array，多维数组），特点：
* 连续内存分配
* 向量化操作
* 布尔选择
* 分片（siceability）

## ndarray基础
* ndarray.ndim，数组轴的个数，在python的世界中，轴的个数被成为*秩*
* ndarray.shape，数组的维度。
* ndarray.size，数组元素的总个数
* ndarray.dtype，一个用来描述数组中元素类型的对象，可以通过创造或制定dtype使用标准python类型，另外Numpy提供他自己的数据类型
* ndarray.itemsize，数组中每个元素的字节大小
* ndarray.data，包含实际数组元素的缓冲区，通常我们不需要使用这个属性，因为我们总是通过索引来使用数组中的元素

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4],dtype=np.int)

In [3]:
type(x)

numpy.ndarray

In [4]:
x.ndim

1

In [5]:
x.shape

(4,)

In [6]:
x.size

4

In [7]:
x.dtype

dtype('int32')

In [8]:
x.data

In [9]:
x.itemsize

4

In [10]:
y = np.arange(12).reshape(3,4)

In [11]:
y.ndim

2

In [12]:
y.size

12

In [13]:
np.size(y)

12

In [14]:
np.size(y,0)# 几行

3

In [15]:
np.size(y,1)# 几列

4

In [16]:
y.shape

(3, 4)

In [17]:
y.itemsize

4

In [18]:
y.data

In [19]:
x1 = np.array(x,dtype=np.float)

In [20]:
x1.dtype,x.dtype

(dtype('float64'), dtype('int32'))

# 创建数组

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
np.ones((2,3),dtype=np.int)

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.full((3,4),'a')

array([['a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a']], dtype='<U1')

In [26]:
np.full((4,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [27]:
np.eye(3)#单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.ones_like(y)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [29]:
np.zeros_like(x)

array([0, 0, 0, 0])

In [30]:
np.full_like(y,8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [31]:
np.linspace(1,50,50)# [1,50]，等间距 填充数据

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [32]:
np.linspace(1,50,50,endpoint = False)# [1,50)

array([ 1.  ,  1.98,  2.96,  3.94,  4.92,  5.9 ,  6.88,  7.86,  8.84,
        9.82, 10.8 , 11.78, 12.76, 13.74, 14.72, 15.7 , 16.68, 17.66,
       18.64, 19.62, 20.6 , 21.58, 22.56, 23.54, 24.52, 25.5 , 26.48,
       27.46, 28.44, 29.42, 30.4 , 31.38, 32.36, 33.34, 34.32, 35.3 ,
       36.28, 37.26, 38.24, 39.22, 40.2 , 41.18, 42.16, 43.14, 44.12,
       45.1 , 46.08, 47.06, 48.04, 49.02])

In [33]:
np.concatenate((x,x1))# 数组 连接

array([1., 2., 3., 4., 1., 2., 3., 4.])

In [34]:
np.concatenate((a,b),axis=1)

array([[ 0.,  1.,  2.,  3.,  0.,  0.,  0.],
       [ 4.,  5.,  6.,  7.,  0.,  0.,  0.],
       [ 8.,  9., 10., 11.,  0.,  0.,  0.]])

In [35]:
np.concatenate((a.T,b))

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

# 数组变换

* 维度变换

In [36]:
a.flatten()# 讲数组降维 到一维数组

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
b.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
a.reshape((4,3))# 返回（4,3）形状的数组，元数组不变

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
a.resize((2,6))# 原数组 shape改变
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [40]:
c = np.arange(20).reshape(4,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [41]:
c.swapaxes(0,1)

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [42]:
c.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

* 改变元素类型

In [43]:
a.astype(np.int)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [44]:
a.astype(np.float)

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

* 改为 list

In [45]:
ls = c.tolist()
type(ls),type(c)

(list, numpy.ndarray)

# 随机数组

* 随机创建

In [46]:
np.random.rand(3,4)

array([[0.42008599, 0.93646296, 0.81975582, 0.02844824],
       [0.12450802, 0.39170384, 0.98313882, 0.38775393],
       [0.91299879, 0.07151202, 0.68864438, 0.75416065]])

In [47]:
np.random.seed(1)
np.random.randn(3,4)

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862],
       [ 0.86540763, -2.3015387 ,  1.74481176, -0.7612069 ],
       [ 0.3190391 , -0.24937038,  1.46210794, -2.06014071]])

In [48]:
np.random.seed(1)
np.random.randn(3,4)

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862],
       [ 0.86540763, -2.3015387 ,  1.74481176, -0.7612069 ],
       [ 0.3190391 , -0.24937038,  1.46210794, -2.06014071]])

In [49]:
np.random.randint(100,200,(3,4))

array([[194, 196, 186, 113],
       [109, 107, 163, 161],
       [122, 157, 101, 100]])

In [50]:
np.random.randint(100,200,50)

array([160, 181, 108, 188, 113, 147, 172, 130, 171, 103, 170, 121, 149,
       157, 103, 168, 124, 143, 176, 126, 152, 180, 141, 182, 115, 164,
       168, 125, 198, 187, 107, 126, 125, 122, 109, 167, 123, 127, 137,
       157, 183, 138, 108, 132, 134, 110, 123, 115, 187, 125])

In [51]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

* 随机排列

In [52]:
np.random.shuffle(c)# 对数组的第1轴进行随机排列
c

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [53]:
np.random.shuffle(c)# 对数组的第1轴进行随机排列
c

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4]])

In [54]:
np.random.permutation(c)

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
z = np.arange(50)
np.random.choice(z,(2,2),0.5)
# 从一维数组z中，一概率p抽取元素，形成size形状新数组

array([[13,  3],
       [ 0, 13]])

* 创建按 规律分布 的随机数组

In [56]:
np.random.uniform(2,100,(5,4))# 均匀分布，最小取值2，最大取值100，形状（5,4）

array([[ 6.4438814 , 15.71667968, 79.65555141,  4.9205331 ],
       [88.54629663, 54.99724258, 45.90205778, 89.42931546],
       [39.00326543, 54.76562004, 65.92529044, 37.40357998],
       [57.958839  , 64.50797544, 14.37885873, 69.6400496 ],
       [65.47944118, 36.6860307 , 76.79683917, 36.94010891]])

In [57]:
np.random.normal(100,2,(3,4))# 正态分布 ，均值 100 标准差2

array([[100.99345271, 100.65855161,  99.99762018,  99.38541475],
       [ 99.632926  ,  98.8940497 ,  99.68857439, 101.14478455],
       [101.51991095, 101.47136399, 102.02778486,  98.52313764]])

In [58]:
np.random.poisson(8,(3,4))# 泊松分布

array([[ 4,  8,  5,  5],
       [ 6, 10,  8,  5],
       [ 8,  7,  6,  7]])

# ndarray 运算

* 一维数组

In [59]:
d = np.random.randint(-20,20,(3,4))
d

array([[-10, -16,   3,  -6],
       [  1, -17,   4,  -4],
       [ -5, -13,  -6,  -7]])

In [60]:
np.abs(d)

array([[10, 16,  3,  6],
       [ 1, 17,  4,  4],
       [ 5, 13,  6,  7]])

In [61]:
np.fabs(d)

array([[10., 16.,  3.,  6.],
       [ 1., 17.,  4.,  4.],
       [ 5., 13.,  6.,  7.]])

In [62]:
np.sqrt(d)

array([[       nan,        nan, 1.73205081,        nan],
       [1.        ,        nan, 2.        ,        nan],
       [       nan,        nan,        nan,        nan]])

In [63]:
np.square(d)

array([[100, 256,   9,  36],
       [  1, 289,  16,  16],
       [ 25, 169,  36,  49]], dtype=int32)

In [64]:
e = np.linspace(50,99,40).reshape(8,5)
e

array([[50.        , 51.25641026, 52.51282051, 53.76923077, 55.02564103],
       [56.28205128, 57.53846154, 58.79487179, 60.05128205, 61.30769231],
       [62.56410256, 63.82051282, 65.07692308, 66.33333333, 67.58974359],
       [68.84615385, 70.1025641 , 71.35897436, 72.61538462, 73.87179487],
       [75.12820513, 76.38461538, 77.64102564, 78.8974359 , 80.15384615],
       [81.41025641, 82.66666667, 83.92307692, 85.17948718, 86.43589744],
       [87.69230769, 88.94871795, 90.20512821, 91.46153846, 92.71794872],
       [93.97435897, 95.23076923, 96.48717949, 97.74358974, 99.        ]])

In [65]:
np.ceil(e)# 向上取整

array([[50., 52., 53., 54., 56.],
       [57., 58., 59., 61., 62.],
       [63., 64., 66., 67., 68.],
       [69., 71., 72., 73., 74.],
       [76., 77., 78., 79., 81.],
       [82., 83., 84., 86., 87.],
       [88., 89., 91., 92., 93.],
       [94., 96., 97., 98., 99.]])

In [66]:
np.floor(e)# 向下取整

array([[50., 51., 52., 53., 55.],
       [56., 57., 58., 60., 61.],
       [62., 63., 65., 66., 67.],
       [68., 70., 71., 72., 73.],
       [75., 76., 77., 78., 80.],
       [81., 82., 83., 85., 86.],
       [87., 88., 90., 91., 92.],
       [93., 95., 96., 97., 99.]])

In [67]:
np.rint(e)# 四舍五入

array([[50., 51., 53., 54., 55.],
       [56., 58., 59., 60., 61.],
       [63., 64., 65., 66., 68.],
       [69., 70., 71., 73., 74.],
       [75., 76., 78., 79., 80.],
       [81., 83., 84., 85., 86.],
       [88., 89., 90., 91., 93.],
       [94., 95., 96., 98., 99.]])

In [68]:
x1,x2 = np.modf(e)# 将整数部分和小数部分 分成独立的两个 数组
x1,x2

(array([[0.        , 0.25641026, 0.51282051, 0.76923077, 0.02564103],
        [0.28205128, 0.53846154, 0.79487179, 0.05128205, 0.30769231],
        [0.56410256, 0.82051282, 0.07692308, 0.33333333, 0.58974359],
        [0.84615385, 0.1025641 , 0.35897436, 0.61538462, 0.87179487],
        [0.12820513, 0.38461538, 0.64102564, 0.8974359 , 0.15384615],
        [0.41025641, 0.66666667, 0.92307692, 0.17948718, 0.43589744],
        [0.69230769, 0.94871795, 0.20512821, 0.46153846, 0.71794872],
        [0.97435897, 0.23076923, 0.48717949, 0.74358974, 0.        ]]),
 array([[50., 51., 52., 53., 55.],
        [56., 57., 58., 60., 61.],
        [62., 63., 65., 66., 67.],
        [68., 70., 71., 72., 73.],
        [75., 76., 77., 78., 80.],
        [81., 82., 83., 85., 86.],
        [87., 88., 90., 91., 92.],
        [93., 95., 96., 97., 99.]]))

In [69]:
np.sign(d)#各元素符号值

array([[-1, -1,  1, -1],
       [ 1, -1,  1, -1],
       [-1, -1, -1, -1]])

# 拼接

In [70]:
a = np.arange(9).reshape(3,3)
b = (a+1)*10
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [71]:
np.vstack([a,b])# 上下堆叠

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [72]:
np.hstack([a,b])# 左右拼接

array([[ 0,  1,  2, 10, 20, 30],
       [ 3,  4,  5, 40, 50, 60],
       [ 6,  7,  8, 70, 80, 90]])

In [73]:
np.concatenate((a,b),axis = 0)# 连接

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [74]:
np.concatenate((a,b),axis = 1)

array([[ 0,  1,  2, 10, 20, 30],
       [ 3,  4,  5, 40, 50, 60],
       [ 6,  7,  8, 70, 80, 90]])

In [75]:
np.dstack((a,b))# 每行，对应位置结合

array([[[ 0, 10],
        [ 1, 20],
        [ 2, 30]],

       [[ 3, 40],
        [ 4, 50],
        [ 5, 60]],

       [[ 6, 70],
        [ 7, 80],
        [ 8, 90]]])

In [76]:
c = np.arange(5)
d = (c+1)*10
np.column_stack((c,d))# 行 结合

array([[ 0, 10],
       [ 1, 20],
       [ 2, 30],
       [ 3, 40],
       [ 4, 50]])

In [77]:
np.column_stack((a,b))

array([[ 0,  1,  2, 10, 20, 30],
       [ 3,  4,  5, 40, 50, 60],
       [ 6,  7,  8, 70, 80, 90]])

In [78]:
np.row_stack((c,d))# 列 

array([[ 0,  1,  2,  3,  4],
       [10, 20, 30, 40, 50]])

In [79]:
np.row_stack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

# 序列化

In [80]:
np.save('e.npy',e)

In [81]:
np.savez('e',a=e,b=d)

In [82]:
np.load('e.npy')

array([[50.        , 51.25641026, 52.51282051, 53.76923077, 55.02564103],
       [56.28205128, 57.53846154, 58.79487179, 60.05128205, 61.30769231],
       [62.56410256, 63.82051282, 65.07692308, 66.33333333, 67.58974359],
       [68.84615385, 70.1025641 , 71.35897436, 72.61538462, 73.87179487],
       [75.12820513, 76.38461538, 77.64102564, 78.8974359 , 80.15384615],
       [81.41025641, 82.66666667, 83.92307692, 85.17948718, 86.43589744],
       [87.69230769, 88.94871795, 90.20512821, 91.46153846, 92.71794872],
       [93.97435897, 95.23076923, 96.48717949, 97.74358974, 99.        ]])

In [83]:
a1 = np.load('e.npz')

In [84]:
a1['a'],a1['b']

(array([[50.        , 51.25641026, 52.51282051, 53.76923077, 55.02564103],
        [56.28205128, 57.53846154, 58.79487179, 60.05128205, 61.30769231],
        [62.56410256, 63.82051282, 65.07692308, 66.33333333, 67.58974359],
        [68.84615385, 70.1025641 , 71.35897436, 72.61538462, 73.87179487],
        [75.12820513, 76.38461538, 77.64102564, 78.8974359 , 80.15384615],
        [81.41025641, 82.66666667, 83.92307692, 85.17948718, 86.43589744],
        [87.69230769, 88.94871795, 90.20512821, 91.46153846, 92.71794872],
        [93.97435897, 95.23076923, 96.48717949, 97.74358974, 99.        ]]),
 array([10, 20, 30, 40, 50]))

In [85]:
np.savetxt('1.csv',e,fmt='%d',delimiter=',')# 存为csv

In [86]:
np.loadtxt('1.csv',dtype=np.float,delimiter=',')# 读取

array([[50., 51., 52., 53., 55.],
       [56., 57., 58., 60., 61.],
       [62., 63., 65., 66., 67.],
       [68., 70., 71., 72., 73.],
       [75., 76., 77., 78., 80.],
       [81., 82., 83., 85., 86.],
       [87., 88., 90., 91., 92.],
       [93., 95., 96., 97., 99.]])

# 数据过滤——布尔选择器

In [87]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [88]:
arr1 < 2

array([ True, False, False, False, False, False])

In [89]:
(arr1 <2) | (arr1 >4)

array([ True, False, False, False,  True,  True])

In [90]:
arr1[arr1>2]

array([3, 4, 5, 6])

In [91]:
np.sum(arr1<4)

3

In [92]:
arr2 = np.arange(12).reshape(2,6)

In [93]:
arr1 == arr2[1,:]

array([False, False, False, False, False, False])

In [94]:
arr3 = np.arange(9).reshape(3,3)
arr4 = np.arange(9,0,-1).reshape(3,3)

In [95]:
arr3 < arr4

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

# 切片

In [96]:
x = np.arange(10)
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [97]:
x[::2]

array([0, 2, 4, 6, 8])

In [98]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [99]:
x[:6]

array([0, 1, 2, 3, 4, 5])

In [100]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
x[-2:]

array([8, 9])

In [102]:
y = np.arange(20).reshape(4,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [103]:
y[:,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [104]:
y[1:4,1:4:2]

array([[ 6,  8],
       [11, 13],
       [16, 18]])

In [105]:
y[-1:0:-2,:]

array([[15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9]])

# reshape

In [106]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
y = x.reshape(2,5)

In [108]:
y.reshape(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
y.ravel()# 展开数组 #指向同一存储空间

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [111]:
np.size(y)

10

In [112]:
reshaped = y.reshape(np.size(y))
raveled = y.ravel()
raveled,reshaped

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [113]:
reshaped[1] = 100 #指向同一存储空间
raveled[2] = 200 #指向同一存储空间
y

array([[  0, 100, 200,   3,   4],
       [  5,   6,   7,   8,   9]])

In [114]:
y

array([[  0, 100, 200,   3,   4],
       [  5,   6,   7,   8,   9]])

In [115]:
reshaped,raveled

(array([  0, 100, 200,   3,   4,   5,   6,   7,   8,   9]),
 array([  0, 100, 200,   3,   4,   5,   6,   7,   8,   9]))

In [116]:
flattened = y.flatten()# 展开
flattened[1] = 1000
flattened

array([   0, 1000,  200,    3,    4,    5,    6,    7,    8,    9])

In [117]:
y

array([[  0, 100, 200,   3,   4],
       [  5,   6,   7,   8,   9]])

# 通用函数

In [118]:
m = np.arange(10,19).reshape(3,3)
print(m)
print('{0} min of the entire matrix'.format(m.min()))
print("{0} max of entire matrix".format(m.max()))
print('{0} position of the min value'.format(m.argmin()))
print('{0} position of the max value'.format(m.argmax()))
print('{0} mins down each column'.format(m.min(axis = 0)))
print('{0} maxs down each column'.format(m.max(axis = 0)))
print('{0} maxs across each row'.format(m.max(axis =1)))

[[10 11 12]
 [13 14 15]
 [16 17 18]]
10 min of the entire matrix
18 max of entire matrix
0 position of the min value
8 position of the max value
[10 11 12] mins down each column
[16 17 18] maxs down each column
[12 15 18] maxs across each row


In [119]:
a = np.arange(1,10)
a.mean(), a.std(), a.var()# 均值，标准差，方差

(5.0, 2.581988897471611, 6.666666666666667)

In [120]:
a.sum(), a.prod() # 和，乘积

(45, 362880)

In [121]:
a.cumsum(), a.cumprod()# 累加，累积

(array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32),
 array([     1,      2,      6,     24,    120,    720,   5040,  40320,
        362880], dtype=int32))

In [122]:
(a<5).any()

True

In [123]:
(a<5).all()

False

# 其它
* 基本统计 cov，mean，std，var
* 基本线性代数 cross，dot，outer，svd，vdot
* 创建array,arange,array.copy,empty,empty_like,eye,frofile,fromfuncation,identity,linspace,mgrid,ogrid,ones,ones_like,zeros,zeros_like
* 操作array split,column stack, concatenate,diagonal,dsplit,dstack,hstack,item,newaxis,ravel,repeat,reshape,resize,squeeze,swapaxes,take,transpose,vsplit,vstack
* all,any,nonzero,where
* choose,compress,cumprod,cumsum,inner,fill,imag,prod,put,putmask,reat,sum